apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-sa
  namespace: logging
  labels:
    app: fluentbit-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-cr
  labels:
    app: fluentbit-cr
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit-crb
roleRef:
  kind: ClusterRole
  name: fluentbit-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentbit-sa
  namespace: logging
